### ISSUE TITLE
403 Forbidden : https://mixxx.org/manual/latest/

### ISSUE THREAD

**Issue by esbrandt** [mixxxdj/manual#111]
**Forbidden**

You don't have permission to access this resource.
Apache/2.4.29 (Ubuntu) Server at mixxx.org Port 80

Same when trying to reach https://mixxx.org/manual/

**Comment by Holzhaus** [comment]
Something on the server is wrong.

https://mixxx.org/manual/2.2/en/ gives 404 Not Found.

**Comment by Holzhaus** [comment]
Should be fixed now.
