### ISSUE TITLE
Fast-Forward/-Rewind buttons are not used in skins anymore

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/manual#124]
so we should either remove the chapter [3.1.5. Transport Controls](https://www.mixxx.org/manual/latest/en/chapters/user_interface.html#transport-controls)
or
mention the buttons were removed from currents skins but can be mapped with controllers/keyboards.
A link to [wiki/mixxxcontols ](https://github.com/mixxxdj/mixxx/wiki/mixxxcontrols#channeln) would also help, I notice don't have that Btw that link should be added to [14.1. Adding support for your MIDI/HID Controller](https://www.mixxx.org/manual/latest/en/chapters/advanced_topics.html#adding-support-for-your-midi-hid-controller)

**Comment by deborahtrez** [comment]
Hi @ronso0 , I'm an Outreachy 2020 applicant, I would like to request to have this issue assigned to me, if it's okay. I can edit the manuals to either remove that section or describe the second option of mentioning that the buttons were removed but can be mapped. 
Thank you.

**Comment by deborahtrez** [comment]
Thank you. Let me get on it
