### ISSUE TITLE
Add infos on new options in Sound Hardware Preferences

### ISSUE THREAD

**Issue by esbrandt** [mixxxdj/manual#13]
- Headphone Delay, mixxxdj/c5e00a30362375ad1dc8a442d6d6514081dd2af8
- Master Delay, mixxxdj/c5e00a30362375ad1dc8a442d6d6514081dd2af8
- Multi-Soundcard Sync,  mixxxdj/mixxx#219
- Master Mix, mixxxdj/mixxx#229
- Keylock Engine,  mixxxdj/mixxx#236
- Master Mono, mixxxdj/mixxx#315

**Comment by Be-ing** [comment]
Also explain the difference between auxiliary, microphone, and vinyl inputs.

**Comment by Be-ing** [comment]
Who can document these? @daschuer ?

**Comment by daschuer** [comment]
https://github.com/mixxxdj/manual/pull/53
