### ISSUE TITLE
Broken link in Readme.md 

### ISSUE THREAD

**Issue by UdokaVrede** [mixxxdj/manual#138]
I am an outreachy applicant for the december cohort, while setting up, I noticed the link to `Retext` points to a broken page. However while searching, I found the official repository for Retext https://github.com/retext-project/retext. I could make a Pull request to fix this.
![eror](https://user-images.githubusercontent.com/63649352/95555099-2f54c480-0a09-11eb-9760-d99daff92af5.png)

**Comment by Be-ing** [comment]
Thanks for noticing this. You don't need to open an issue for small tasks like this, just go ahead and make a pull request to fix it. (If you want to make large changes affecting many parts of the manual, it would be good to discuss those on Zulip before spending time working on them.)

**Comment by UdokaVrede** [comment]
Alright thanks, I apologise for this.

**Comment by Holzhaus** [comment]
>  I apologise for this

No need to apologize, it's not possible to know all details of a project's preferred workflow beforehand, so it's learning by doing 😉 Thank you for you work!

**Comment by UdokaVrede** [comment]
Hi @Holzhaus @Be-ing I have made a P.R for this. Thanks
