### ISSUE TITLE
Document Intro/Outro markers

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/manual#146]
Where added in https://github.com/mixxxdj/mixxx/pull/1242 (Mixxx 2.3)
They should be mentioned
* in https://www.mixxx.org/manual/2.3/en/chapters/user_interface.html?highlight=hotcues#waveform-displays
* in https://www.mixxx.org/manual/2.3/en/chapters/user_interface.html?highlight=hotcues#playback-cue-controls
* added to the [Glossary](https://www.mixxx.org/manual/2.3/en/glossary.html#glossary-of-terms) and linked whereever they're mentioned

**Comment by Holzhaus** [comment]
Note: This needs to go into the `manual-2.3.x` branch, not `manual-2.2.x` as it's a new feature in Mixxx 2.3.

**Comment by Be-ing** [comment]
I'm not sure I agree they should be added to the User Interface chapter. It takes too many words to explain how to use them.

**Comment by Be-ing** [comment]
The text is mostly already written at https://mixxx.org/news/2020-07-09-intro-outro-sections/ and needs to be adapted for the manual.

**Comment by Holzhaus** [comment]
> I'm not sure I agree they should be added to the User Interface chapter. It takes too many words to explain how to use them.

I think we should add it to the UI chapter for now. In the long term, the manual should probably be restructured so that Decks, Samplers, etc. all get their own (sub-)chapter.

**Comment by ronso0** [comment]
Yes, we should mention them there and link to the AutoDJ chapter later on where the usage is explained.

**Comment by Be-ing** [comment]
> I think we should add it to the UI chapter for now.

> In the long term, the manual should probably be restructured so that Decks, Samplers, etc. all get their own (sub-)chapter.

**Comment by Goodiec** [comment]
@Be-ing can I work on this?

**Comment by Be-ing** [comment]
You do not need to ask to work on something unless someone else has said they're already working on it.

**Comment by Goodiec** [comment]
> You do not need to ask to work on something unless someone else has said they're already working on it.

OK, thank you
