### ISSUE TITLE
Update screenshots to use the default skin

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/manual#153]
Default skins:
2.2.x Deere
2.3.x LateNight, PaleMoon theme

**Comment by LizzyKate** [comment]
I will work on this issue

**Comment by LizzyKate** [comment]
> Default skins:
> 2.2.x Deere
> 2.3.x LateNight, PaleMoon theme

I will work on this. Thanks

**Comment by ronso0** [comment]
Thanks @LizzyKate 
I suggest you start with a PR targeted at 2.2.x
Let us know if you need any help.

**Comment by deborahtrez** [comment]
Hey @LizzyKate i had started working on updating chapter 3 for this issue [here](https://github.com/mixxxdj/manual/pull/154), you can skip it, and update the other chapters, if its no bother :) .

**Comment by deborahtrez** [comment]
Thank you for assigning this to me  😃

**Comment by ronso0** [comment]
...well, forgot about that earlier & you almost finished it for 2.2 :)
