### ISSUE TITLE
Add missing Key information to Decks chapter

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/manual#217]
Key info is missing here
https://www.mixxx.org/manual/2.2/en/chapters/user_interface.html#track-information-display

**Comment by deborahtrez** [comment]
Hi @ronso0 , i hope you're okay. 
I saw that this issue points to a pull request i made a few days ago. I'm happy to work on this issue with some guidance. Is it a documentation problem?
What key information needs to be added to the chapter?

**Comment by ronso0** [comment]
Yes, great! Please add info about Key and Cover Art, as well.

**Comment by deborahtrez** [comment]
> Yes, great! Please add info about Key and Cover Art, as well.

Awesome. Thank you for assigning this to me. Let me get started on it.

**Comment by deborahtrez** [comment]
Hi @ronso0 i worked on this issue inside PR #154 . And committed the changes. I thought it would be easier to work on all the requested changes at that moment on the same branch. I hope this is okay with you. Just waiting on your approval.... :)

**Comment by ronso0** [comment]
#154
