### ISSUE TITLE
reasonable order for chapters in 3.2. The Mixer Section

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/manual#238]
current order:
![image](https://user-images.githubusercontent.com/5934199/96755279-cc810700-13d2-11eb-8811-6e5584968574.png)

* new order to bundle channel controls:
> 3.2.1. Channel Faders and Level Meters
3.2.2. Equalizers and Gain Knobs
3.2.3. PFL/Headphone Button
3.2.4. Crossfader
3.2.5. Headphone and Master Mix Controls

* move "3.2.2. Section Expansion Buttons" to the bottom of  **3. An Overview of the Mixxx Interface**

**Comment by ulomau** [comment]
Please i am an oitreachy applicant, can i work on this issue?

**Comment by ronso0** [comment]
Welcome @ulomau !
I have just assigned this bug to you. Simple [open a PR](https://github.com/mixxxdj/manual/pulls) and let us know in case you need help.

**Comment by ulomau** [comment]
Okay thank you
