### ISSUE TITLE
DJing With Mixxx has become a dump settings descriptions

### ISSUE THREAD

**Issue by kain88-de** [mixxxdj/manual#24]
We explain a lot of the different settings in the `Djing with mixxx` chapter. Eg Bpm settings. This is intuitive. It takes me a while to find the settings descriptions by just looking at the TOC of the manual.

All this stuff should be moved to `Configuring Mixxx` and then referenced in `Djjing with Mixxx`.

**Comment by esbrandt** [comment]
I don't think we should just move it from ``Djjing with Mixxx``to ``Configuring Mixxx`` but add a separate ``Preferences`` section instead. This way it is easier to keep the ever-changing preferences settings up-to-date, also for feature maintainers.

I refactored the manual for v1.11, and changed all references to link to a newly written preferences section explaining **all** the options, but did not finish in time of the 1.11 release. And then life happened.

Probably still have the changes on backup. Just wanted to throw this in before someone starts writing all this stuff down again.

**Comment by kain88-de** [comment]
It would be really nice if you can find these changes. If you can upload them I will see that I find time to incorporate them into the current version.

**Comment by Be-ing** [comment]
Fixed by https://github.com/mixxxdj/manual/pull/34
