### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by Holzhaus** [mixxxdj/manual#240]
Some broken links in the manual-2.2.x branch:

```
source/chapters/appendix.rst.rst:440: WARNING: broken link: https://bugs.launchpad.net/mixxx/+bug/16878282 (404 Client Error: Not Found for url: https://bugs.launchpad.net/mixxx/+bug/16878282)
source/chapters/hardware.rst.rst:45: WARNING: broken link: https://mixxx.org/wiki/doku.php/start#controller_mapping_documentation (Anchor 'controller_mapping_documentation' not found)
source/chapters/library.rst.rst:923: WARNING: broken link: https://mixxx.org/wiki/doku.php/compiling_on_linux#optionalbuild_with_m4a_aac_file_support (Anchor 'optionalbuild_with_m4a_aac_file_support' not found)
source/chapters/livebroadcasting.rst.rst:295: WARNING: broken link: https://mega.nz/#!WdwHHTzA!UkdJwUQiihwHb0ShdOBTYj8noSwXluxiKjdWvFQRgOU (HTTPSConnectionPool(host='mega.nz', port=443): Read timed out. (read timeout=5))
```

**Comment by championshuttler** [comment]
Can i work on it for outreachy?

**Comment by Holzhaus** [comment]
> Hi @Holzhaus  Can i work on it for outreachy?

Sure, go ahead.

I'm unsure about that mega.co.nz link, I opened a Zulip Discussion for it: https://mixxx.zulipchat.com/#narrow/stream/109176-documentation/topic/mega.2Eco.2Enz.20link.20in.20the.20manual

**Comment by Holzhaus** [comment]
> > Hi @Holzhaus  Can i work on it for outreachy?
> 
> Sure, go ahead.
> 
> I'm unsure about that mega.co.nz link, I opened a Zulip Discussion for it: https://mixxx.zulipchat.com/#narrow/stream/109176-documentation/topic/mega.2Eco.2Enz.20link.20in.20the.20manual

Replace the `mega.co.nz` link with `https://lame.sourceforge.io/links.php#Binaries`.

**Comment by Goodiec** [comment]
Created a pull request for this issue, please review.
