### ISSUE TITLE
add description for Vinyl and Passthrough buttons

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/manual#270]
...in https://www.mixxx.org/manual/latest/en/chapters/user_interface.html#vinyl-control-mode-and-cueing-controls

(after #154 is merged)

**Comment by Goodiec** [comment]
@ronso0 would like to work on this, can this issue be assigned to me?

**Comment by Holzhaus** [comment]
OK cool, go ahead :D

**Comment by deborahtrez** [comment]
Hi @ronso0 @Holzhaus, how're you?
Is this issue meant to stay open? I saw that the PR for this was merged. Does it still need some work?

**Comment by ronso0** [comment]
Hej @deborahtrez , thanks for the reminder. Closed
