### ISSUE TITLE
update Command Line Options with explicit commands for Windows & macOS

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/manual#272]
currently https://mixxx.org/manual/latest/en/chapters/appendix.html#command-line-options assumes Linux.

**Comment by Goodiec** [comment]
@ronso0 will like to work on this, is there a resource available to get the command line alternatives for the other operating systems?

**Comment by Holzhaus** [comment]
@ronso0 Can you elaborate? Where does it asumme Linux?

**Comment by ronso0** [comment]
Sorry for being unclear.
A few days ago when I was trying to help a user on the forum and also when doing remote macOS debugging on Zulip, I noticed that we have no documentation about the exact 'mixxx' base command users need to enter into the terminal prompt to which they'd append the command line options.

It would be nice to have specific examples for macOS, Linux & Windows, like
`%PROGRAMFILES%\Mixxx\mixxx.exe` / `%PROGRAMFILES(x86)%\Mixxx\mixxx.exe`  and
`/Applications/Mixxx.app/Contents/MacOS/mixxx` / `% open -a Mixxx.app`
(I don't know which is more generic = always works)

**Comment by deborahtrez** [comment]
> Sorry for being unclear.
> A few days ago when I was trying to help a user on the forum and also when doing remote macOS debugging on Zulip, I noticed that we have no documentation about the exact 'mixxx' base command users need to enter into the terminal prompt to which they'd append the command line options.
> 
> It would be nice to have specific examples for macOS, Linux & Windows, like
> `%PROGRAMFILES%\Mixxx\mixxx.exe` / `%PROGRAMFILES(x86)%\Mixxx\mixxx.exe` and
> `/Applications/Mixxx.app/Contents/MacOS/mixxx` / `% open -a Mixxx.app`
> (I don't know which is more generic = always works)

Hi @ronso0 @Holzhaus , this is how I was able to open Mixxx in developer mode. I use Windows.
![image](https://user-images.githubusercontent.com/28389950/100709893-ecd3b680-33bf-11eb-858f-e970c47c5bc0.png)

but this is not mentioned anywhere in the documentation. I got this from one of the forums. 
I can add this to that chapter if you give me the go-ahead (for Windows at least). For instance the full command for  `--controllerDebug` would be `mixxx --controllerDebug`

**Comment by ronso0** [comment]
Sure, go ahead! I'm sure you can collect correct info for macOS, too, if you ask on Zulip.
I think for each platform we only need the "base command" once, the actual command options table in the manual can stay as it is.

**Comment by deborahtrez** [comment]
Alright. Thank you! I'm on it. Hi @ywwg I will be starting with this. I will be opening a PR soon.

**Comment by ronso0** [comment]
resolved by #313
