### ISSUE TITLE
Fix broken Links in 2.3 branch

### ISSUE THREAD

**Issue by Holzhaus** [mixxxdj/manual#285]
There are a lot of broken links in the `manual-2.3.x` branch that should be fixed.

**Comment by Goodiec** [comment]
@Holzhaus would like to work on this in this [pull request](https://github.com/mixxxdj/manual/pull/253) as the request is failing the linkcheck test as a result of this issue but noticed that most of the links that are identified as broken are anchor links that actually open up correctly, so how can this be fixed?

**Comment by Holzhaus** [comment]
Is the anchor correct? For github wiki, we need to add `user-content` or something like that in front of the link. Check the merged PR that fixes the broken links for the 2.2 branch.

**Comment by Goodiec** [comment]
> Is the anchor correct? For github wiki, we need to add `user-content` or something like that in front of the link. Check the merged PR that fixes the broken links for the 2.2 branch.

Yes, it is but adding user-content also opens it up.

**Comment by Holzhaus** [comment]
#300 fixes most of the markup issues and broken wiki links. There are still a lot of links that are down though.
