### ISSUE TITLE
Move Standard effects mapping documentation into manual

### ISSUE THREAD

**Issue by Holzhaus** [mixxxdj/manual#289]
Some controllers (e. g. the Roland DJ-505) use our Standard Effects Mapping. As the controller documentation has been moved into 2.3 manual, the standard effects mapping should be documented in the manual as well.

https://github.com/mixxxdj/mixxx/wiki/Standard-Effects-Mapping

**Comment by ronso0** [comment]
Yes, let's also add some images

**Comment by deborahtrez** [comment]
Hi @ronso0  and @Holzhaus i would like to work on this. Should this be moved to the 'Effects' chapter?

**Comment by ronso0** [comment]
I think **11.5 Controller Effects Mapping** would suit better

**Comment by Be-ing** [comment]
Either works IMO, but whichever place it is not should have a link to the place where it is.
