### ISSUE TITLE
mention mp3 encoder in Recording chapter

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/manual#293]
mention mp3 encoder in [Libary > Recording](https://manual.mixxx.org/2.2/en/chapters/library.html#recordings) and [recording-your-mix](https://manual.mixxx.org/2.2/en/chapters/djing_with_mixxx.html#recording-your-mix)

just stumbled upon this when a user didn't have the mp3 options in Preferences
https://mixxx.discourse.group/t/bitrate-how-do-i-sdet-a-bitrate-need-to-record-at-320-kbps-constant-bit-raate/20228/4

**Comment by deborahtrez** [comment]
Hi @ronso0 I would like to work on this issue, if it's okay with you. How do i approach this task? 
I read the conversation in the discourse group but I'm still not quite sure how you would want it mentioned in the chapters....

**Comment by ronso0** [comment]
In the manual we should mention that Preferences > Recording only show available encoders, so if users don't see the MP3 option they obviously don't have an mp3 encoder installed. IMO it would be helpful to point that out (only available oncoders are listed) and add a link to https://manual.mixxx.org/2.2/en/chapters/livebroadcasting.html#activate-mp3-streaming-support
And I notice it's actually [DJing with MIxxx > Recording...](https://manual.mixxx.org/2.2/en/chapters/djing_with_mixxx.html#recording-your-mix) where that link should be.

Btw that chapter could use some clean up. There's a lot of stuff mentioned there but it feels like it's missing some structure. 
Maybe try to look at it with the eyes of a beginner: after the introduction, what are the most important aspects we should mention first, besides pointing to Preferences > Recording? ("Recording And Broadcasting With An External Hardware..." is probably NOT a topic requested  by most users and thus could be moved down IMO.

**Comment by ronso0** [comment]
> Hi @ronso0 I would like to work on this issue, if it's okay with you. 

Sure, go ahead. anyone's allowed to pick an Issue. If the respective PR is opened we'd assign that Issue to the contributor. (most of the times that's not necessary, linking the PR and the Issue should suffice.

**Comment by deborahtrez** [comment]
> Btw that chapter could use some clean up. There's a lot of stuff mentioned there but it feels like it's missing some structure.
> Maybe try to look at it with the eyes of a beginner: after the introduction, what are the most important aspects we should mention first, besides pointing to Preferences > Recording? ("Recording And Broadcasting With An External Hardware..." is probably NOT a topic requested by most users and thus could be moved down IMO.

I agree with you on this. This is very similar to the concern that @Holzhaus had about this chapter - structure. https://github.com/mixxxdj/manual/issues/335#issuecomment-753356752
I'm going to go through each of the sub-sections under this chapter and see if the order needs revision. While I do so, perhaps it will also help me establish clear differences between this chapter and the cookbook chapter (my project). I will open up a topic in the documentation stream in case I need some guidance before making the PR.

**Comment by deborahtrez** [comment]
> In the manual we should mention that Preferences > Recording only show available encoders, so if users don't see the MP3 option they obviously don't have an mp3 encoder installed. IMO it would be helpful to point that out (only available oncoders are listed) and add a link to https://manual.mixxx.org/2.2/en/chapters/livebroadcasting.html#activate-mp3-streaming-support

Hi @ronso0 so i tried to record a mix to try to understand this better. I have the MP3 option in Preferences > Recording

![image](https://user-images.githubusercontent.com/28389950/103894475-0cb57300-5100-11eb-9dac-55b58ee7b796.png)

.... even without the mp3 encoder installed...

![image](https://user-images.githubusercontent.com/28389950/103895271-31f6b100-5101-11eb-8c29-44c6f4210f29.png)

Should I still go ahead and include it?
It might be helpful to add that last screenshot to give more context to the not having the mp3 encoder installed. (Personally, i only understood that part after I got that pop-up). What do you think?
