### ISSUE TITLE
Add Screenshot of FX routing to effects documentation

### ISSUE THREAD

**Issue by Holzhaus** [mixxxdj/manual#320]
The effect routing buttons are easy to overlook. We should add screenshots to the manual, to make it more obvious. 

Forum thread where a user overlooked the FX routing buttons: https://mixxx.discourse.group/t/effect-rack-1-doesnt-work-for-deck-1-yet-works-in-headphones-master/20409

**Comment by deborahtrez** [comment]
Hi @Holzhaus  is this the screenshot that should be added?

![image](https://user-images.githubusercontent.com/28389950/103444725-693a0d80-4c7c-11eb-895e-14cff63b3bac.png)

Maybe we can add a description that says "To route deck 1 to effect unit 1, click the `FX1` button to turn it on. To route deck 2 to effect unit 2. click the `FX2` button.... and so on....?

**Comment by Holzhaus** [comment]
Yes, but maybe add a little context around it (e.g. that the total image size is doubled or something like that). That makes it easier to find on screen.

**Comment by deborahtrez** [comment]
Okay. 
I'm afraid I haven't understood what you mean by "the total image size is doubled.."
Do you mean when the "4 Effect Units" is toggled in the settings menu, the total image size is doubled, which makes it easier to find on screen?

**Comment by Holzhaus** [comment]
RIght now the picture is 63x52px. If you make a screenshot with ~120x100px *where the buttons still have the same size* (so that you can also see a bit of the surrounding UI elements), it's easier to see where the buttons can be found on screen.

**Comment by deborahtrez** [comment]
Ohh okay. I've understood. Let me do that. Thank you.

**Comment by Holzhaus** [comment]
Btw, I think two FX units is the default, right? Maybe we should use a screenshot with just FX1/FX2.

**Comment by deborahtrez** [comment]
Yes, two FX units is the default. 
Alright.

**Comment by deborahtrez** [comment]
Hey @Holzhaus should I include screenshots of the effect unit buttons located in the microphone and auxiliary sections of the skin as well?
I added one screenshot of the ones located in the deck section. The description of the issue says .. "we should add screenshot**s**..."

**Comment by Holzhaus** [comment]
They look the same, so I don't think it's necessary.

**Comment by deborahtrez** [comment]
Alright.

**Comment by deborahtrez** [comment]
The PR for this is here. https://github.com/mixxxdj/manual/pull/336
Ready for review.... :)
