### ISSUE TITLE
Reasonable re-arrangement of 'Live Broadcasting' chapter.

### ISSUE THREAD

**Issue by deborahtrez** [mixxxdj/manual#335]
I will be moving "DJing with Mixxx" inside the cookbook chapter.
The Cookbook, by definition, gives Mixxx users examples that they can work off of. And this chapter seems to fit there better....

hi @Holzhaus  can I go ahead with this?

**Comment by Be-ing** [comment]
I was thinking of maybe taking the opposite approach and splitting the sections of the "DJing with Mixxx" chapter into their own chapters.

**Comment by Holzhaus** [comment]
I have a hard time understanding why the manual is structured the way it is. For example, why is broadcasting a separate chapter but Recording is not?
In general, I'd rather see if we can reorganize the manual instead of just adding more chapters. 

I think the mixing techniques/cookbook content that's not really specific to Mixxx should all go into a single separate chapter.
The Mixxx-specific stuff should be moved elsewhere (e.g. "Recording your Mix").

Btw, our files are really long and hard to navigate. The new mixing chapter could be split into separate files in by using `include` or `toctree` directives.

**Comment by deborahtrez** [comment]
Hi @Holzhaus @Be-ing .  I've been thinking of a better structure for some of the chapters and sections in the manual, especially for Djing with Mixxx and the Broadcasting chapter. And this is what I came up with...

"Live Broadcasting - start your own internet radio" is a chapter of its own, but "Recording your mix" is not, even though I feel like they are somewhat similar.
What if "Record/ Broadcast your mix" was one entire chapter with this format:

10.1: Recording your mix (pulled from DJing with Mixxx, chapter 12 - it could be mentioned here as a tip/note/hint with a reference to this chapter)
10.1.1: Record your mix to disk

10.2: Live Broadcast - Start your own mix
10.2.1: Streaming services
10.2.2: Configuring Mixxx
10.2.3: Live Broadcasting
10.2.4: Preferences
10.2.5: Troubleshooting

10.3: Recording and broadcasting with an external Hardware Mixer (pulled from Using Microphones chapter 9 - it is kind of hidden in this chapter, so I felt like it would fit better here). This section would top it all off.

How do feel about this arrangement?

**Comment by Holzhaus** [comment]
Thanks, looks good so far.

Just a few questions:

> 10.1.1: Record your mix to disk

What is the reason for this subsection if recording to disk is the only way to record your mix? ;-)

> 10.2.2: Configuring Mixxx
> [...]
> 10.2.4: Preferences

Isn't that basically the same? These should be merged IMHO.

> 10.2.3: Live Broadcasting

Where does this subsection come from? What does it contain? Considering that the whole section is about live broadcasting, this section should have a more descriptive title I think.

> 10.3: Recording and broadcasting with an external Hardware Mixer (pulled from Using Microphones chapter 9 - it is kind of hidden in this chapter, so I felt like it would fit better here). This section would top it all off.

I'm unsure about moving it. It also fits in the other chapter. Maybe we can add a `.. seealso:` box in the "Configuring Mixxx" subsection?

**Comment by deborahtrez** [comment]
> > 10.1.1: Record your mix to disk
> 
> What is the reason for this subsection if recording to disk is the only way to record your mix? ;-)

I can merge these into just one section. 

`10.1: Record your mix`

> > 10.2.2: Configuring Mixxx
> > [...]
> > 10.2.4: Preferences
> 
> Isn't that basically the same? These should be merged IMHO.
> 
> > 10.2.3: Live Broadcasting
> 
> Where does this subsection come from? What does it contain? Considering that the whole section is about live broadcasting, this section should have a more descriptive title I think.

We can then proceed to make these ...
`10.2: Streaming Servers`

`10.3: Configuring Mixxx`
      `10.3.1: Live Broadcasting preferences`
           `10.3.1.1: Icecast Vs. Shoutcast`
           `10.3.1.2: Broadcast directories`


`10.4: Troubleshooting`

`10.5: Activate mp3 streaming support`

> > 10.3: Recording and broadcasting with an external Hardware Mixer (pulled from Using Microphones chapter 9 - it is kind of hidden in this chapter, so I felt like it would fit better here). This section would top it all off.
> 
> I'm unsure about moving it. It also fits in the other chapter. Maybe we can add a `.. seealso:` box in the "Configuring Mixxx" subsection?

Alright.
Hi @Holzhaus I have made revisions to the format. Is this one okay?

**Comment by Holzhaus** [comment]
> > > 10.1.1: Record your mix to disk
> > 
> > 
> > What is the reason for this subsection if recording to disk is the only way to record your mix? ;-)
> 
> I can merge these into just one section.
> 
> `10.1: Record your mix` 

:+1:
 
> We can then proceed to make these ...
> `10.2: Streaming Servers`
> 
> `10.3: Configuring Mixxx`
> `10.3.1: Live Broadcasting preferences`
> `10.3.1.1: Icecast Vs. Shoutcast`
> `10.3.1.2: Broadcast directories`
> 
> `10.4: Troubleshooting`
> 
> `10.5: Activate mp3 streaming support`

From the user's perspective, I cannot tell what the difference between 10.3 and 10.3.1 is. If both sections are about configuration, we could just do this:

- 10.2: Live Broadcasting - Start your own mix
  - 10.1: Streaming Servers
  - 10.2: Configuring Mixxx
    - 10.2.1 Server Connection
    - 10.2.2 Stream Settings
    - 10.2.3 Encoding
    - 10.2.4 Metadata
      - 10.2.4.1 Shoutcast metadata format
      - 10.2.4.2 Custom Metadata
    - 10.2.5 Custom metadata
    - 10.2.6: Broadcast directories
  - 10.3: Troubleshooting

The text from the "Icecast vs Shoutcast" could be split up and put into "Server Connection" section where you explain the "Type" and the "Encoding" section where the "Format" is mentioned.

What do you think?

> `10.5: Activate mp3 streaming support`

Are you planning to do the changes in the 2.3 branch? If so, that section can be removed I think, because liblame/MP3 support is shipped with Mixxx from 2.3 IIRC.

**Comment by deborahtrez** [comment]
>       * 10.2.4.2 Custom Metadata
>     * 10.2.5 Custom metadata

Do these two sections have different content?
Where will [Icecast vs. Shoutcast](https://manual.mixxx.org/2.2/en/chapters/livebroadcasting.html#icecast-vs-shoutcast) go to? Will it be under 10.2.5?

**Comment by deborahtrez** [comment]
> Are you planning to do the changes in the 2.3 branch? If so, that section can be removed I think, because liblame/MP3 support is shipped with Mixxx from 2.3 IIRC.

I'm thinking maybe I should work in the 2.2 branch, so that the changes are merged with 2.3, then I will work inside the 2.3 branch to delete the "Activate mp3 streaming support" section? What do you think?

**Comment by Holzhaus** [comment]
Sounds good to me.

**Comment by deborahtrez** [comment]
> > Are you planning to do the changes in the 2.3 branch? If so, that section can be removed I think, because liblame/MP3 support is shipped with Mixxx from 2.3 IIRC.
> 
> .......... then I will work inside the 2.3 branch to delete the "Activate mp3 streaming support" section? @Holzhaus What do you think?

It looks like this had already been taken care of. https://manual.mixxx.org/2.3/en/chapters/livebroadcasting.html
