### ISSUE TITLE
Change screenshots in 2.3 to default "LateNight" skin

### ISSUE THREAD

**Issue by deborahtrez** [mixxxdj/manual#355]
The default skin for Mixxx 2.3 is the Latenight skin. Shouldn't we change the screenshots from the Deere to the Latenight skin? especially for Chapter 3.

**Comment by Holzhaus** [comment]
Yes, see #220 and #117.

**Comment by deborahtrez** [comment]
Ohhh. 😅I had forgotten that I had opened the exact same issue months back. 😅
