### ISSUE TITLE
broken link to http://banshee.fm

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/manual#365]
Discovered by CI.
I think it should be 
https://www.banshee-project.org/

```
/home/runner/work/manual/manual/source/chapters/library.rst.rst:872: WARNING: broken link: http://banshee.fm/ (HTTPConnectionPool(host='banshee.fm', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb7645a9fd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname')))
```

**Comment by StarTrooper08** [comment]
Hello , I m new too Mixxxdj community. I like to contribute to open source can I get started with my first contribution to Mixxxdj with the Mixxxdj/manual issue no #365

**Comment by Holzhaus** [comment]
@StarTrooper08 sure, go ahead and open a PR 👍

**Comment by ronso0** [comment]
@StarTrooper08 See https://github.com/mixxxdj/manual/tree/2.3#readme for getting started

**Comment by StarTrooper08** [comment]
Is this link need to be changed?


![IMG_20210403_000428](https://user-images.githubusercontent.com/72031540/113463314-c2176e80-9442-11eb-9366-808e41829e15.jpg)

Files from repository manual - source / chapters / library.rst line no 864.

**Comment by Holzhaus** [comment]
Yes.

**Comment by StarTrooper08** [comment]
> @StarTrooper08 See https://github.com/mixxxdj/manual/tree/2.3#readme for getting started

    Can I make PR for this??

**Comment by Holzhaus** [comment]
> @StarTrooper08 sure, go ahead and open a PR 👍

**Comment by StarTrooper08** [comment]
Done

**Comment by StarTrooper08** [comment]
Please have a look over the PR🙂.

**Comment by Holzhaus** [comment]
Thanks, merged.

**Comment by StarTrooper08** [comment]
Welcome , I will try to work on another issue.
