### ISSUE TITLE
Check that all keyboard shortcuts are properly documented

### ISSUE THREAD

**Issue by ferranpujolcamins** [mixxxdj/manual#38]
Check that all keyboard shortcuts are properly documented where the corresponding Mixxx function is explained. Also provide an appendix with a reference list of all the available keyboard shortcuts.

**Comment by hannydevelop** [comment]
Hello @ferranpujolcamins  I am an outreachy applicant, can I work on this issue

**Comment by ferranpujolcamins** [comment]
Sure! Please go ahead.

**Comment by hannydevelop** [comment]
Thank you so much, I am glad to make this issue my first outreachy contribution. could you please add an assigned label to this issue, I am working on this already. can this project be my contribution for the project "Improve User Manual". Thank you

**Comment by hannydevelop** [comment]
Hello @ronso0 and @Holzhaus can final review be made and this Pull Request merged? I need to open a pull request for https://github.com/mixxxdj/manual/issues/137

**Comment by ronso0** [comment]
I reopen this because I think we should also consolidate some strayed shortcuts which are not in the keyboard overview.
For example GUI section toggles, Record Mix, skin settings menu etc.

**Comment by hannydevelop** [comment]
Ok!

**Comment by ronso0** [comment]
You don't need to tackle this now.

Don't ge me wrong: your PR is okay.
It's only I just noticed that some shortcuts are not documented anywhere (at least I don't find them).
Let's not rush this, I think we also need to update some tooltips.

**Comment by hannydevelop** [comment]
No Problem, the goal is to get better while working on this project. I will
work on this until it is well documented!
