### ISSUE TITLE
page-not-found not styled

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/manual#395]
see:
https://manual.mixxx.org/2.3/en/chapters/hardware/controllers/#page-not-found

**Comment by ronso0** [comment]
also, from that page there is no easy way back to the respective chapter, the genrated links in the language, version and release sections are useless
https://manual.mixxx.org/2.3/en/chapters/hardware/controllers/chapters/chapters/introduction.html

**Comment by ICTman1076** [comment]
I have begun #407 to help fix this, but it will not play nice with the multiple languages in its current state.

**Comment by Holzhaus** [comment]
The issue is that the urls to images/styles/etc are relative. So it works for https://manual.mixxx.org/2.3./en/foo but not for https://manual.mixxx.org/2.3/en/foo/bar. We probably just need to override html_baseurl.

**Comment by Holzhaus** [comment]
And also add a 404 page for non existing versions to the `build_html.sh` file.
