### ISSUE TITLE
fix macOS settings directory path

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/manual#451]
old path (<=2.2.x) is still shown in
https://manual.mixxx.org/2.3/en/chapters/advanced_topics.html#adding-support-for-your-midi-hid-controller
https://manual.mixxx.org/2.3/en/chapters/advanced_topics.html#deleting-your-library
and other places?

Users upgrading to 2.3 won't notice it's the wrong directory because it's populated with Mixxx files?
https://bugs.launchpad.net/mixxx/+bug/1950047

**Comment by frspp** [comment]
"Users upgrading to 2.3 won't notice it's the wrong directory because it's populated with Mixxx files?"
No it is not populated. I created the folder as per Manual instructions.

**Comment by ronso0** [comment]
okay, thanks. 
though the manual doesn't instruct to _create_ that folder.

**Comment by frspp** [comment]
True. I have used some application before where you need to create the folder.

**Comment by ronso0** [comment]
@frspp Could you please check https://github.com/mixxxdj/manual/pull/454 wether the paths are correct now?
