### ISSUE TITLE
Mention vinyl control audio pass-through and how to use it

### ISSUE THREAD

**Issue by Pegasus-RPG** [mixxxdj/manual#49]
The manual is lacking mention of the pass-through feature of vinyl control. Add a section describing what it is and how to use it.

**Comment by asantoni** [comment]
+1 - Being able to "use Mixxx as a mixer replacement" is huge.

On Thu, Dec 3, 2015 at 12:12 PM, Sean M. Pappalardo <
notifications@github.com> wrote:

> The manual is lacking mention of the pass-through feature of vinyl
> control. Add a section describing what it is and how to use it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mixxxdj/manual/issues/49>.
>



-- 
Albert Santoni
Developer, Mixxx
http://www.mixxx.org
http://www.oscillicious.com

**Comment by ronso0** [comment]
See #126 targeting 2.2/2.3
