### ISSUE TITLE
403 - Forbidden when pushing to mixxxdj/manual.git

### ISSUE THREAD

**Issue by esbrandt** [mixxxdj/manual#51]
Suddenly:
``Pushing to https://esbrandt@github.com/mixxxdj/manual.git
remote: Permission to mixxxdj/manual.git denied.
fatal: unable to access 'https://esbrandt@github.com/mixxxdj/manual.git/': The requested URL returned error: 403 - Forbidden``

Whats going on here guys, anything i should know of?

**Comment by rryan** [comment]
Hang on I think I messed something up, sorry!

**Comment by rryan** [comment]
Sorry, fixed!

**Comment by esbrandt** [comment]
Still 403
Looks like members of the ``Mixxx DJ Software team Documentation```
can only read and clone, but not push.
https://github.com/orgs/mixxxdj/teams/documentation/repositories

**Comment by rryan** [comment]
Arg, try now?

**Comment by esbrandt** [comment]
fixed, thanks

**Comment by Goutham-Elangovan** [comment]
Can anyone explain whats the fix?

**Comment by kuldeep-taroko** [comment]
@Goutham-Elangovan I suppose its the issue because of the wrong password. Please enter the password again

**Comment by ramkrishnakuldeep** [comment]
@Goutham-Elangovan I suppose its the issue because of the wrong password. Please enter the password again.
