### ISSUE TITLE
mixbot writes corrupt changelog.rst files, which let Sphinx / Build Check fail and inhibits generation of preview

### ISSUE THREAD

**Issue by JoergAtGithub** [mixxxdj/manual#553]
How can we prevent, that mixbot can commit files, that break builds of HEAD?
https://github.com/mixxxdj/manual/actions/runs/4378433738/jobs/7665114625?pr=550

**Comment by Swiftb0y** [comment]
Should be straightforward, seems to me like we're just missing an underscore? https://github.com/sphinx-doc/sphinx/issues/3921

**Comment by JoergAtGithub** [comment]
Is it intended, that the Sphinx checks are only executed for Pull-Request:
https://github.com/mixxxdj/manual/blob/2.3/.github/workflows/sphinx.yml
This way nobody will see if a push breaks the buildability until a Pull-Request is based on this branch.

**Comment by Swiftb0y** [comment]
`.github/workflows/build.yml` builds and deploys on each push iiuc.

**Comment by JoergAtGithub** [comment]
Yes, it builds and deploys, but doesn't check the code using Sphinx. Therefore the CI runs of the branches pass, but all PRs based on them fail.

**Comment by Swiftb0y** [comment]
I don't understand, shouldn't the build fail then? I don't quite understand the difference.

**Comment by JoergAtGithub** [comment]
If I understand it correct these are different runners.
-sphinx.yml only checks the code
-build.xml builds the HTML output and deploys it

The failure is only detected by Sphinx, but not during the HTML generation - and Sphinx is not executed for pushes.

**Comment by Swiftb0y** [comment]
but build.xml uses sphinx to build the html and pdf outputs. So why does it not fail while building?

**Comment by JoergAtGithub** [comment]
@daschuer The 2.4 changelog broke again the manual builds:
`Warning: /home/runner/work/manual/manual/source/chapters/appendix/changelog.rst:10: WARNING: Duplicate explicit target name: "#11460".`
