### ISSUE TITLE
microphone ducking

### ISSUE THREAD

**Issue by Be-ing** [mixxxdj/manual#57]
There is no documentation about how to use mic ducking and the difference between manual and auto modes.

https://bugs.launchpad.net/mixxx/+bug/1764609

**Comment by ywwg** [comment]
this came up in the facebook group recently, a radio DJ thought we didn't have this feature because it wasn't in the manual

**Comment by Be-ing** [comment]
There are now tooltips for this. You could likely copy and paste the text from those (with minimal adaptation).

**Comment by Holzhaus** [comment]
Related Zulip Chat: https://mixxx.zulipchat.com/#narrow/stream/109695-_support/topic/troubleshooting.20autoduck/near/213657544

**Comment by deborahtrez** [comment]
Hey @Holzhaus @ywwg @Be-ing . Can this issue be assigned to me? I would be happy to work on this :)

**Comment by Holzhaus** [comment]
> Hey @Holzhaus @ywwg @Be-ing . Can this issue be assigned to me? I am happy to work on this if its okay with you :)

Cool, I assigned the issue to you.

> Should this be documented under Chapter 9: Using Microphones ?

Yes, that makes sense.

**Comment by deborahtrez** [comment]
> > Hey @Holzhaus @ywwg @Be-ing . Can this issue be assigned to me? I am happy to work on this if its okay with you :)
> 
> Cool, I assigned the issue to you.
> 
> > Should this be documented under Chapter 9: Using Microphones ?
> 
> Yes, that makes sense.

Thank you! On it!

**Comment by ronso0** [comment]
@deborahtrez Do you have an audio setup to test this with?

**Comment by deborahtrez** [comment]
> @deborahtrez Do you have an audio setup to test this with?

i'm using my headphones, that have an inbuilt microphone. When i talk, i can hear the ducking effect, on auto mode. The other modes work too. The level of volume to which the music reduces can be adjusted with the Strength knob.  

Still trying to figure out how to record both my voice and the music on the same channels, in a recording. but i can do this another time.

**Comment by ywwg** [comment]
you should be able to make a Mixxx Recording to combine your voice and the music in one file: https://www.mixxx.org/manual/latest/en/chapters/djing_with_mixxx.html?highlight=recording#recording-your-mix

**Comment by deborahtrez** [comment]
> you should be able to make a Mixxx Recording to combine your voice and the music in one file: https://www.mixxx.org/manual/latest/en/chapters/djing_with_mixxx.html?highlight=recording#recording-your-mix

Thank you @ywwg .

**Comment by deborahtrez** [comment]
Here is the [pull request](https://github.com/mixxxdj/manual/pull/247) for this issue.
