### ISSUE TITLE
The Numark Party Mix User Guide link is broken

### ISSUE THREAD

**Issue by fwcd** [mixxxdj/manual#587]
The link check currently [fails](https://github.com/mixxxdj/manual/actions/runs/6443421780/job/17495363337) with the following message (reformatted for better readability):

```
/home/runner/work/manual/manual/source/hardware/controllers/numark_party_mix.rst:4:
  WARNING: broken link:
    https://www.numark.com/images/product_downloads/Party_Mix_-_User_Guide_-_v1.1.pdf
      (HTTPSConnectionPool(host='www.numark.com', port=443):
  Max retries exceeded with url:
    /images/product_downloads/Party_Mix_-_User_Guide_-_v1.1.pdf
      (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]
      certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)'))))
```

This is particularly strange since [the link](https://www.numark.com/images/product_downloads/Party_Mix_-_User_Guide_-_v1.1.pdf) seems to work perfectly fine in a browser, whereas both CURL and the Sphinx check fail. With `openssl s_client -connect www.numark.com:443` we can inspect the certificate chain:

```
Certificate chain
 0 s:CN = www.numark.com
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = GeoTrust TLS RSA CA G1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jul 17 00:00:00 2023 GMT; NotAfter: Aug 16 23:59:59 2024 GMT
```

I found a Stack Exchange post that discusses essentially the same issue and it seems as if the Numark servers are incorrectly configured to not include all intermediate certificates in the chain of trust:

https://serverfault.com/questions/509158/unable-to-locally-verify-the-issuers-authority-for-geotrust-ssl-ca

Further reading for the curious:

- https://www.reddit.com/r/devops/comments/mpsk4o/does_a_ssl_certificate_chain_require_a_root/
- https://security.stackexchange.com/questions/162592/why-do-i-need-to-add-intermediate-ca-certificates-to-jvms-cacerts-file

Not sure how to best deal with this (aside from waiting for Numark to fix their servers). I can think of two immediate workarounds, though neither of them is particularly pretty:

- Use HTTP for the link. The user will be redirected to HTTPS anyway and Sphinx apparently doesn't follow the redirect for the certificate check (?).
- Skip the certificate check (can this be done on a per-link basis?)

**Comment by daschuer** [comment]
If using the http link works, this should be a good workaround. Else I would just skip the link check.
