### ISSUE TITLE
library#auto-dj-automate-your-mix - 2

### ISSUE THREAD

**Issue by RafaelFrance** [mixxxdj/manual#663]
2.4 manual
https://manual.mixxx.org/2.4/fr/chapters/library#auto-dj-automate-your-mix
In 
By default, Auto DJ removes tracks after playing them but if you want it to play the same tracks over and over again, you can activate the :guilabel:`Auto DJ Requeue` option in :menuselection:`Preferences --> Auto DJ --> Re-queue tracks after playback`.
The part
"... you can activate the :guilabel:`Auto DJ Requeue` option in :menuselection:`Preferences --> Auto DJ --> Re-queue tracks after playback`." 
is not in accordance with GUI

**Comment by ronso0** [comment]
Dupe of #670 ?

**Comment by RafaelFrance** [comment]
Yes, it seems.
Sorry.

**Comment by ronso0** [comment]
Thanks.
