### ISSUE TITLE
djing_with_mixxx#auto-dj - 1

### ISSUE THREAD

**Issue by RafaelFrance** [mixxxdj/manual#668]
2.4 manual
https://manual.mixxx.org/2.4/fr/chapters/djing_with_mixxx#auto-dj
Update screenshot "Mixxx library - Auto DJ view"

**Comment by ronso0** [comment]
Fixed by https://github.com/mixxxdj/manual/commit/e9a5fb65e30766428f37f980fb34492875fbb113
