### ISSUE TITLE
djing_with_mixxx#playing-tracks-in-auto-dj - 2

### ISSUE THREAD

**Issue by RafaelFrance** [mixxxdj/manual#670]
2.4 manual
https://manual.mixxx.org/2.4/en/chapters/djing_with_mixxx#playing-tracks-in-auto-dj
Update 
You can add a track to the end of the Auto DJ playlist once it is played instead of removing it. Set :menuselection:`Preferences --> Auto DJ --> Re-queue tracks after playback --> On`.
There are several setting in the "Re-queue tracks after playback" section in Preference.

**Comment by ronso0** [comment]
I'm not sure what you're saying.
Do you propose to add another option "Re-queue tracks after playback"? I.e. the equivalent to the "Repeat" toggle in the AutoDJ interface?

**Comment by ronso0** [comment]
Ah okay, sorry, didn't see that section. (and confused it with #663 ??)

Anyhow, shoudl be fixed by #684
