### ISSUE TITLE
vinyl_control#supported-timecode-media (Pioneer RekordBox DVS is missing)

### ISSUE THREAD

**Issue by Russe** [mixxxdj/manual#692]
https://manual.mixxx.org/2.4/en/chapters/vinyl_control#supported-timecode-media

At 2.4 manual there is Pioneer RekordBox DVS Control Vinyl missing. Could you please add this to the manual as well the responsiveness?

**Comment by ronso0** [comment]
Adding the entry is easy. For evaluating the responsiveness I created this thread in the forums
https://mixxx.discourse.group/t/how-responsive-are-rekordbox-control-vinyls-in-mixxx/30196

**Comment by Russe** [comment]
As there's still no reply at discourse it seems that RekordBox DVS Control is not in use by many people.
Maybe it can be added to the manual with responsiveness "unknown"?

**Comment by ronso0** [comment]
Sure, done.
https://github.com/mixxxdj/manual/commit/3f0fbf0d7f5e1f54e7cfd91e62d1f8968b8438cd
