### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by Holzhaus** [mixxxdj/manual#88]
I'm currently writing a sphinx extension that allows us to build multiple versions of the manual.

What tags/branches do we need? I guess all tags and the master branch. I'll mark the tag with the highest version number as the latest version.

We can use that information to show a warning for all other tags that this is an outdated version of the manual. For all branches we can show a warning that it's a development version.

Can we switch to standard versioning tag names (`v2.2.3` instead of `release-2.2.3`)? That would make parsing easier and will look better in the version switcher.

**Comment by Holzhaus** [comment]
Pinging @daschuer because you requested that feature ;-)

**Comment by rryan** [comment]
How much harder is it to stick with our current name scheme? The benefit is that it matches our main repo, and we wouldn't have to change anything in Jenkins.

**Comment by rryan** [comment]
> I'm currently writing a sphinx extension that allows us to build multiple versions of the manual.
> 
> What tags/branches do we need? I guess all tags and the master branch. I'll mark the tag with the highest version number as the latest version.

I'm not clear on what this means -- would building the manual in a given branch imply building all previous versions of the manual?

We currently use a Jenkins job per-version to build and deploy the manual in each supported language to the website -- how do you see this fitting in with that?

**Comment by Holzhaus** [comment]
> > I'm currently writing a sphinx extension that allows us to build multiple versions of the manual.
> > What tags/branches do we need? I guess all tags and the master branch. I'll mark the tag with the highest version number as the latest version.
> 
> I'm not clear on what this means -- would building the manual in a given branch imply building all previous versions of the manual?

Not necessarily. You can still build the manual as usual, which will only build the manual for current HEAD.

However, to get nice sidebar links to switch between versions, each manual needs to know about the other versions. Also, we don't want to make changes to old tags so we can't change `conf.py` or the theme for these versions.

Hence, I'm currently making a wrapper that invokes sphinx that builds all whitelisted tags/branches with the sphinx conf file and theme in HEAD. 

> We currently use a Jenkins job per-version to build and deploy the manual in each supported language to the website -- how do you see this fitting in with that?

I have to look into that. I'm not sure how the different languages work atm.

**Comment by Holzhaus** [comment]
> How much harder is it to stick with our current name scheme? The benefit is that it matches our main repo, and we wouldn't have to change anything in Jenkins.

OK, I can probably parse the tag names with a regex.

But tbh I still don't understand the pattern behind the tag/branch names. I thought that we had a tag are for each release, but only have 3 `release-<version>` tags. We also have a bunch of `manual-<version>` branches (these are not matching our main repo Btw) and no master branch. Which ones am I supposed to build?
For example, are you currently using `manual-2.0.x` or `release 2.0.0`to build https://www.mixxx.org/manual/2.0/ ?

**Comment by rryan** [comment]
> However, to get nice sidebar links to switch between versions, each manual needs to know about the other versions. Also, we don't want to make changes to old tags so we can't change `conf.py` or the theme for these versions.
>
> Hence, I'm currently making a wrapper that invokes sphinx that builds all whitelisted tags/branches with the sphinx conf file and theme in HEAD.

Hm, would that mean we need to preserve buildability of all our manual release branches going forward? Given we'll need to switch to Python 3 eventually, this would mean we'd have to upgrade old branches to Python 3 only for this switcher feature.

**Comment by rryan** [comment]
> But tbh I still don't understand the pattern behind the tag/branch names. I thought that we had a tag for each release, but we only have 3 release-<version> tags. We also have a bunch of manual-<version> branches (their names are not matching our main repo btw) and no master branch. Which ones am I supposed to build?

Yea, I guess we don't really have a need / purpose for the release tags after all.

> For example, are you currently using `manual-2.0.x` or `release-2.0.0` to build https://www.mixxx.org/manual/2.0/ ?

Yea, the HEAD of `manual-2.0.x` branch is used to build https://www.mixxx.org/manual/2.0/  every time you kick off the jenkins job that publishes the manual. (that job doesn't exist anymore because we deleted all of the 2.0.x jobs in Jenkins). This is so that we can keep improving the manual for the 2.0.x after individual point releases of Mixxx. 

(For example [manual-2.1-publish](https://builds.renegadetech.mixxx.org/job/v2.1/job/manual-2.1-publish/) on Jenkins)

**Comment by Holzhaus** [comment]
> > However, to get nice sidebar links to switch between versions, each manual needs to know about the other versions. Also, we don't want to make changes to old tags so we can't change `conf.py` or the theme for these versions.
> > Hence, I'm currently making a wrapper that invokes sphinx that builds all whitelisted tags/branches with the sphinx conf file and theme in HEAD.
> 
> Hm, would that mean we need to preserve buildability of all our manual release branches going forward? Given we'll need to switch to Python 3 eventually, this would mean we'd have to upgrade old branches to Python 3 only for this switcher feature.

No, you can build the old branches using the current settings using the `-c` argument: just give it the config path of the *latest* config, but use the `sourcedir` of the old version. The only downside is that `version` and `release` are set in the config, so these values will be wrong. But my extension will take care of that.

Here's an example for the 1.1.0 manual that I built with the current config:
![2020-02-19-10-25-55_3840x2160](https://user-images.githubusercontent.com/1834516/74820495-6c493b00-5302-11ea-8ad2-7bffe65b260f.png)

**Comment by Holzhaus** [comment]
> > But tbh I still don't understand the pattern behind the tag/branch names. I thought that we had a tag for each release, but we only have 3 release- tags. We also have a bunch of manual- branches (their names are not matching our main repo btw) and no master branch. Which ones am I supposed to build?
> 
> Yea, I guess we don't really have a need / purpose for the release tags after all.

Ok, so I'll only take branches in to account (and ignore all tags).
I can match them with a regex like `manual-(\d+).(\d+|x).(\d+|x)`, but we could also think about using branch names like `2.2` as we do on the main repo.

Can we introduce a `master` branch for the development version of the manual, as we do on the main repo? Otherwise I can't determine if `manual-2.3.x` is the manual for a release or a development version.

**Comment by daschuer** [comment]
Thank you for working on this.
Just keep in mind that the manual url is compiled into Mixxx
https://github.com/mixxxdj/mixxx/blob/787debc622418e6695bf27eb962fcccdd938534e/src/defs_urls.h#L24

**Comment by rryan** [comment]
Yea, this is kind of complicated by the fact that we shouldn't change the existing URL structure on the website: https://www.mixxx.org/manual/

I'm still unclear on the proposal here (sorry :)) -- would the latest master release job be in charge of publishing all historical versions of the manual?

**Comment by rryan** [comment]
> Can we introduce a `master` branch for the development version of the manual, as we do on the main repo? Otherwise I can't determine if `manual-2.3.x` is the manual for a release or a development version.

Yea, the main reason we don't have a master is so that drive-by contributors don't send PRs to master when they should have gone to an appropriate release branch (sidesteps having to ask them to rebase).

Each time we make a new series, we fork the latest manual-2.y.x to manual-2.(y+1).x and set that to be the default branch on github. Once we establish a new series, the same issue of wrong-branches can occur though. In practice, people don't get started on the manual changes till we're getting very close to a release, so the time period that an unreleased `manual-x.y.z` is the default branch on github is usually pretty small.

**Comment by Holzhaus** [comment]
> Yea, this is kind of complicated by the fact that we shouldn't change the existing URL structure on the website: https://www.mixxx.org/manual/

Don't worry, I made this configurable.

> I'm still unclear on the proposal here (sorry :)) -- would the latest master release Jenkins job be in charge of publishing all historical versions of the manual?

Yes. Check out PR #89, it builds all old versions at once. This is how it works:
1. Clone the repo
2. Run `sphinx-multiversion` instead of `sphinx-build` (same command line arguments)
This will do the following:
    1. Find other branches/tags (whitelisted in the `conf.py`)
    2. Create a tempdir and shallow-clone all different branches/tags into separate folders (from the local repo, so no network traffic should be generated)
    3. Gather all docname and metadata from the different repos and write a metadata file into the tempdir
    4. Run `sphinx-build` for all the cloned repos in the tempdir
    5. A sphinx extension now loads the version metadata from the file and exposes it to the html context (in each spawned sphinx build instance)
3. Instead of writing data directly to the output dir (`build/html`), the data `build/html/2.2/en/` (you can configure a pattern like `{version}/{language}` or `{branchname}`)

You still have to build each *language* separately, but all *versions* are built at once.

**Comment by Holzhaus** [comment]
> Yea, the main reason we don't have a master is so that drive-by contributors don't send PRs to master when they should have gone to an appropriate release branch (sidesteps having to ask them to rebase).

Wouldn't this be mitigated by keeping the current release branch as default branch?

Regard renaming branches from `manual-2.2.x` to just `2.2.x` or `2.2`:  This would have make the version switcher make look nicer. Have a look at the bottom left of this screenshot:
![Mixxx with versioning](https://user-images.githubusercontent.com/1834516/74856539-8efb4400-5342-11ea-9357-39b718952a81.png)

**Comment by rryan** [comment]
> Regard renaming branches from `manual-2.2.x` to just `2.2.x` or `2.2`: This would have make the version switcher make look nicer. Have a look at the bottom left of this screenshot:

Is there a way to use the `version` or `release` from the Sphinx conf.py as the name instead of the branch name? 

I feel like we should try to avoid mentioning branch/tags at all and just talk about versions of the software, since we aren't a library users are less likely to care about what branch they're using. Based on my read of #89 we have control over the template that renders this section, so couldn't we strip the `manual-` prefix from the branch names pretty easily? Or is the template language too limited.

I tend to prefer the status quo because it requires less work overall (people won't need to update their local clones of the repo) if it only takes a small amount of work to make it possible on your part. If the amount of work it will take you to work around this is greater than the sum of the work of all the local clones that need fixing from others then renaming the branches sounds good to me.

**Comment by rryan** [comment]
If we add a master branch, how could we control how it shows up in this list? master is maybe too technical, something like "unreleased" or "development" might make more sense. Would you suggest just naming the branch that? Just another case where the display name of the branch might not match the branch name.

**Comment by rryan** [comment]
> > 
> 
> Yes. Check out PR #89, it builds all old versions at once. This is how it works:
> 
>     1. Clone the repo
> 
>     2. Run `sphinx-multiversion` instead of `sphinx-build` (same command line arguments)
>        This will do the following:
>        
>        1. Find other branches/tags (whitelisted in the `conf.py`)
>        2. Create a tempdir and shallow-clone all different branches/tags into separate folders (from the local repo, so no network traffic should be generated)
>        3. Gather all docname and metadata from the different repos and write a metadata file into the tempdir
>        4. Run `sphinx-build` for all the cloned repos in the tempdir
>        5. A sphinx extension now loads the version metadata from the file and exposes it to the html context (in each spawned sphinx build instance)
> 
>     3. Instead of writing data directly to the output dir (`build/html`), the data `build/html/2.2/en/` (you can configure a pattern like `{version}/{language}` or `{branchname}`)
> 
> 
> You still have to build each _language_ separately, but all _versions_ are built at once.

Sweet, this sounds good. Here's the script that Jenkins runs:

```
#!/bin/bash

# A builder must have:
# - sudo apt-get install python-virtualenv texlive-fonts-recommended texlive-latex-extra
# - A $HOME/.transifexrc with a Transifex API key.
# - the Jenkins "manual" label.

virtualenv ./virtualenv
source ./virtualenv/bin/activate
pip install -r requirements.txt
fab tx_pull 
fab i18n_build

mkdir languages

# Enable language re-direction from https://mixxx.org/manual/x.y/
cp htaccess languages/.htaccess

for language in source/locale/*; do
  language=$(basename $language);
  if [[ "$language" == "pot" ]]; then
    continue
  fi
  fab clean release html:language=${language} pdf:language=${language}
  mv build/html languages/$language
  mv build/latex/*.pdf languages/$language/
done
```
Then the copy rule copies `languages/**/*` to `$HOME/.jenkins/2.3/manual/build-$BUILD_ID/`, and runs this script:
```
VERSION=2.3;

sudo -u mixxx -- mkdir -p /home/mixxx/public_html/manual
# WARNING: --delete will delete everything in the destination path that is not in the source!
# To test changes, MAKE A BACKUP of the forums and wiki, and run with -n (dry run).
sudo -u mixxx -- rsync -arv --delete $HOME/.jenkins/$VERSION/manual/build-$BUILD_ID/ /home/mixxx/public_html/manual/$VERSION

rm -rf .jenkins/$VERSION/manual/build-$BUILD_ID/
```
So it will need some small tweaks to replace the whole mixxx.org/manual directory instead of just a version subdirectory.

**Comment by daschuer** [comment]
How are different languages selected?
Can this also be a part of this feature?

**Comment by Holzhaus** [comment]
> How are different languages selected?
> Can this also be a part of this feature?

Nope, this is out of scope and will make stuff much more complex. I'd rather do that as as a separate extension.

**Comment by Holzhaus** [comment]
> @daschuer: How are different languages selected?
> Can this also be a part of this feature?

Have a look at #94.

**Comment by rryan** [comment]
Looks like you're using Python 3.7 features, and Ubuntu 18.04 is on 3.6.5
https://packages.ubuntu.com/bionic/python3

```
sphinx-multiversion source build/html -b html -d build/doctrees  -D language='ca' -t release -c source
Traceback (most recent call last):
  File "/home/mixxx/workspace/manual-publish/virtualenv/bin/sphinx-multiversion", line 11, in <module>
    load_entry_point('sphinx-multiversion==1.0.0', 'console_scripts', 'sphinx-multiversion')()
  File "/home/mixxx/workspace/manual-publish/virtualenv/lib/python3.6/site-packages/sphinx_multiversion/main.py", line 78, in main
    for gitref in gitrefs:
  File "/home/mixxx/workspace/manual-publish/virtualenv/lib/python3.6/site-packages/sphinx_multiversion/git.py", line 47, in get_refs
    for ref in get_all_refs(gitroot):
  File "/home/mixxx/workspace/manual-publish/virtualenv/lib/python3.6/site-packages/sphinx_multiversion/git.py", line 31, in get_all_refs
    creatordate = datetime.datetime.fromisoformat(fields[2])
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
Makefile:178: recipe for target 'versionedhtml' failed
make: *** [versionedhtml] Error 1

Fatal error: local() encountered an error (return code 2) while executing 'make -e SPHINXOPTS="-D language='ca' -t release" versionedhtml'
```

**Comment by Holzhaus** [comment]
This is resolved.
