### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by rryan** [mixxxdj/manual#90]

**Comment by Holzhaus** [comment]
What is the problem exactly? I'm using Python 3.8 to build the manual and it works just fine.

**Comment by rryan** [comment]
Are you running Fabric commands from Python 3 successfully?

**Comment by rryan** [comment]
It looks like our Transifex config is also broken under Python 3 (I think the newer version of the Transifex tool reject errors in our config that were not errors in the Python 2 version of the tool)

**Comment by rryan** [comment]
> Are you running Fabric commands from Python 3 successfully?

#93 fixes this by switching to a python3-compatible fork of fabric 1.x

**Comment by rryan** [comment]
Updated all Jenkins manual jobs to use Python 3 now.

**Comment by Holzhaus** [comment]
I see install errors in the jenkins jobs. Probably because you're missing support for python wheels:
https://pythonwheels.com/

**Comment by Holzhaus** [comment]
Also:
```
transifex-client-0.13.7 urllib3-1.25.8
tx ERROR: No option 'hostname' in section: 'https://www.transifex.com'

Fatal error: local() encountered an error (return code 1) while executing 'tx pull -a -f'

Aborting.
```

**Comment by rryan** [comment]
Doh! I didn't see that. I think this is an issue with the transifexrc on the builder (not in the repo). Trying a fix now.

**Comment by rryan** [comment]
> I see install errors in the jenkins jobs. Probably because you're missing support for python wheels:
> https://pythonwheels.com/

Yea I saw those and installed `python3-wheel` on the Ubuntu builder, but that didn't seem to fix it. Failure to build wheels seems non-fatal?

**Comment by Holzhaus** [comment]
They probably fall back to the egg format then.

**Comment by rryan** [comment]
> Also:
> 
> ```
> transifex-client-0.13.7 urllib3-1.25.8
> tx ERROR: No option 'hostname' in section: 'https://www.transifex.com'
> 
> Fatal error: local() encountered an error (return code 1) while executing 'tx pull -a -f'
> 
> Aborting.
> ```

My change to .transifexrc to add api_hostname and hostname seems to have fixed this:
```
[https://www.transifex.com]
api_hostname = https://api.transifex.com
hostname = https://www.transifex.com
password = .
username = .
```
https://builds.renegadetech.mixxx.org/job/v2.1/job/manual-2.1-publish/33/console
